<h5>Ali Morajjabi - 610300104</h5>

<hr>

<h3 style="color:#07ff00">Cholsky Factorization</h3>

In [1]:
import numpy as np

In [10]:
def choleskyFactorization(A:np.array):
    
    L = np.zeros((A.shape[0], A.shape[1]))
    for i in range(L.shape[1]):
        L[i][0] = A[i][0]/np.sqrt(A[0][0])
    
    if (A.shape[0] == 1):
        return L
    
    new_A = np.copy(A[1:, 1:])
    d = L[1:, 0]
    new_A -= np.outer(d, d).astype(float)
    L[1:, 1:] = choleskyFactorization(new_A)

    return L

In [11]:
def MSE(x, y):

    _mse = 0
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            _mse += (x[i][j] - y[i][j])**2

    n = x.shape[0]*x.shape[1]
    return _mse / n

In [12]:
A = np.array([[1, 2, 4, 7],
             [2, 13, 23, 38],
             [4, 23, 77, 122],
             [7, 38, 122, 294]])

A_1 = np.array([[1, 1, 1],
                [1, 1.001, 1.001],
                [1, 1.001, 2]])

x = np.linalg.cholesky(A_1)
y = choleskyFactorization(A_1)

In [13]:
print(MSE(x, y))

print(x)
print(y)

5.349805401075655e-36
[[1.         0.         0.        ]
 [1.         0.03162278 0.        ]
 [1.         0.03162278 0.99949987]]
[[1.         0.         0.        ]
 [1.         0.03162278 0.        ]
 [1.         0.03162278 0.99949987]]


In [14]:
# L.T @ x = inv(L) @ b
def solveEquation(A, b):
    L = choleskyFactorization(A)
    right_side = np.linalg.inv(L) @ b
    z = (right_side[2]) / L.T[2][2]
    y = (right_side[1] - z*L.T[1][2]) / L.T[1][1]
    x = (right_side[0] - y*L.T[0][1] - z*L.T[0][2]) / L.T[0][0]
    return np.array((x, y, z))

In [16]:
A = np.array([[1, 1, 1],
            [1, 1.001, 1.001],
            [1, 1.001, 2]])

b = np.array([3, 3.003, 4.001])

answer = solveEquation(A, b)

print(A @ answer)


[3.    3.003 4.001]
